name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Add ChromeDriver to PATH
        run: |
          export PATH=$PATH:/usr/lib/chromium-browser/

      - name: Run Robot Framework tests
        env:
          BROWSER: Chrome
          BROWSER_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-port=9222"
        run: |
          robot -d results -v BROWSER:$BROWSER -v BROWSER_OPTIONS:"$BROWSER_OPTIONS" tests
