name: Robot Framework Tests

on: 
  push 

jobs:	
  tests:
    name: Run Tests #
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository #Clonar arquivos do repositório
        uses: actions/checkout@v2

      - name: Set up Python #Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies #Instalação das dependencias 
        run: |
          pip install robotframework
          pip install robotframework-requests

      - name: Run Robot Framework tests
        run: 
          robot -d results tests

      - name: Archive Robot Framework results #Salvar resultados dos testes
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: robot-results
          path: ./results
