name: Robot Framework Tests

on: 
  push 

jobs:	
  tests:
    name: Run Tests 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-seleniumlibrary
          pip install selenium
          pip install webdriver-manager

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set up /dev/shm
        run: |
          sudo mount -o remount,size=2G /dev/shm

      - name: Start ChromeDriver with Specific Version
        run: |
          python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager('114.0.5735.90').install()"

      - name: Run Robot Framework tests
        env:
          ROBOT_BROWSER_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-port=9222"
          ROBOT_BROWSER: "Chrome"
        run: |
          robot -d results -v BROWSER:Chrome -v BROWSER_OPTIONS:"--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-port=9222" tests

      - name: Archive Robot Framework results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: robot-results
          path: ./results
